/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Entidades.Partido;
import Repositorios.PartidoRepositorio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan
 */
public class CadastroPartido extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPartido
     */
    public CadastroPartido() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPartidos = new javax.swing.JTable();
        btnInserir = new javax.swing.JButton();
        btnAlt = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sigla"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPartidos);

        btnInserir.setLabel("Inserir");
        btnInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInserirMouseClicked(evt);
            }
        });

        btnAlt.setText("Habilitar Alterações");
        btnAlt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAltMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnInserir)
                .addGap(82, 82, 82)
                .addComponent(btnAlt)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlt))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private static boolean alterar = false;
    private void tbPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPartidosMouseClicked
        // TODO add your handling code here:
        if(alterar == true){
            test();
        }
    }//GEN-LAST:event_tbPartidosMouseClicked

    private void btnInserirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbPartidos.getModel();
        PartidoRepositorio partidoRepositorio = new PartidoRepositorio();
        Partido partido = new Partido();
        String nome = null;
        
            nome = JOptionPane.showInputDialog("Insira o Nome:");
        if(nome == null){
            Thread.currentThread().stop();
        }
        partido.setNome(nome);
        String sigla = null;
        
            sigla = JOptionPane.showInputDialog("Insira a Sigla:");
        if(sigla == null){
            Thread.currentThread().stop();
        }
        partido.setSigla(sigla);
        partidoRepositorio.inserir(partido);
        carregarTabela();
    }//GEN-LAST:event_btnInserirMouseClicked

    private void btnAltMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltMouseClicked
        // TODO add your handling code here:
        if(btnAlt.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Clique no campo que deseja alterar.");
            btnAlt.setText("Desabilitar Alterações");
            alterar = true;
        }else{
            btnAlt.setText("Habilitar Alterações");
            alterar = false;
        }
    }//GEN-LAST:event_btnAltMouseClicked

    public void test(){
        PartidoRepositorio partidoRepositorio = new PartidoRepositorio();
        
        Integer row = tbPartidos.getSelectedRow();
        Integer col = tbPartidos.getSelectedColumn();
        String title = (String) tbPartidos.getColumnName(col);
        String nome = (String) tbPartidos.getValueAt(row, 0);
        Partido partido = partidoRepositorio.buscarPorNome(nome);
        
        switch (title) {
            case "Nome":
                String n = JOptionPane.showInputDialog("Digite o novo valor:");
                if(n == null){
                    break;
                }
                partido.setNome(n);
                break;
            case "Sigla":
                String sig = JOptionPane.showInputDialog("Digite o novo valor:");
                if(sig == null){
                    break;
                }
                partido.setSigla(sig);
                break;
            
        }
        
        partidoRepositorio.editar(partido);
        carregarTabela();
    }
    
    public void carregarTabela(){
        PartidoRepositorio partidoRepositorio = new PartidoRepositorio();
        List<Partido> partidos = partidoRepositorio.buscarTudoOrdenado();

        String[] colunasTabela = new String []{"Nome", "Sigla"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }};
        tbPartidos.setModel(modeloTabela);
       
        for (Partido partido : partidos) {
            modeloTabela.addRow(new Object[]{partido.getNome(),partido.getSigla()});   
            }
       }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPartido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPartido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAlt;
    private javax.swing.JButton btnInserir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPartidos;
    // End of variables declaration//GEN-END:variables
}
