/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;


import Entidades.Candidato;
import Entidades.Partido;
import Repositorios.CandidatoRepositorio;
import Repositorios.PartidoRepositorio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Danilo Cardoso
 */

public class CandidatoTela extends javax.swing.JFrame {

    /**
     * Creates new form Candidatos
     */
     public boolean qualquermerda;
    public CandidatoTela() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCandidatos = new javax.swing.JTable();
        btnCandidato = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbCandidatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCandidatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCandidatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCandidatos);

        btnCandidato.setText("Novo Usuario");
        btnCandidato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCandidatoMouseClicked(evt);
            }
        });

        btnExcluir.setText("Excluir Usuario");

        btnEditar.setText("Habilitar Alterações");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnCandidato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluir)
                .addGap(92, 92, 92)
                .addComponent(btnEditar)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCandidato)
                    .addComponent(btnExcluir)
                    .addComponent(btnEditar))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCandidatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCandidatoMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbCandidatos.getModel();
        CandidatoRepositorio candidatoRepositorio = new CandidatoRepositorio();
        Candidato candidato = new  Candidato();
        PartidoRepositorio partidoRepositorio = new PartidoRepositorio();
        String nome = JOptionPane.showInputDialog("Insira o Nome:");
        candidato.setNome(nome);
        String cpf = JOptionPane.showInputDialog("Insira a CPF:");
        candidato.setCpf(cpf);
        String part = JOptionPane.showInputDialog("Insira o partido:");
        Partido partido = new Partido();
        partido = partidoRepositorio.buscarPorSigla(part);
        candidato.setPartido(partido);
        candidatoRepositorio.inserir(candidato);
        carregarTabela();
    }//GEN-LAST:event_btnCandidatoMouseClicked
private static boolean alterar = false;
    private void tbCandidatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCandidatosMouseClicked
        // TODO add your handling code here:
        if(alterar == true){
            test();
        }
    }//GEN-LAST:event_tbCandidatosMouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
          if(btnEditar.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Clique no campo que deseja alterar.");
            btnEditar.setText("Desabilitar Alterações");
            alterar = true;
        }else{
            btnEditar.setText("Habilitar Alterações");
            alterar = false;
        }
    }//GEN-LAST:event_btnEditarMouseClicked
public  void carregarTabela(){
        CandidatoRepositorio candidatoRepositorio = new CandidatoRepositorio();
        List<Candidato> candidatos = candidatoRepositorio.buscarTudoOrdenado();

        String[] colunasTabela = new String []{"Nome", "CPF", "Partido"};
        DefaultTableModel modeloTabela = new DefaultTableModel(null, colunasTabela){};
        tbCandidatos.setModel(modeloTabela);
       
        for (Candidato candidato : candidatos) {
            modeloTabela.addRow(new Object[]{candidato.getNome(),candidato.getCpf(),candidato.getPartido().getSigla()});   
            }
       }
public void test(){
    CandidatoRepositorio candidatoRepositorio = new CandidatoRepositorio();
    PartidoRepositorio partidoRepositorio = new PartidoRepositorio();
        Integer row = tbCandidatos.getSelectedRow();
        Integer col = tbCandidatos.getSelectedColumn();
        String title = (String) tbCandidatos.getColumnName(col);
        String nome = (String) tbCandidatos.getValueAt(row, 0);
        Candidato candidato = candidatoRepositorio.buscarPorNome(nome);
        
        switch (title) {
            case "Nome":
                String n = JOptionPane.showInputDialog("Digite o novo valor:");
                if(n == null){
                    break;
                }
                candidato.setNome(n);
                break;
            case "CPF":
                String cpf = JOptionPane.showInputDialog("Digite o novo valor:");
                if(cpf == null){
                    break;
                }
                candidato.setCpf(cpf);
                break;
            case "Partido":
                String part = JOptionPane.showInputDialog("Insira o partido:");
                if(part == null){
                    break;
                }
                Partido partido = new Partido();
                partido = partidoRepositorio.buscarPorSigla(part);
                candidato.setPartido(partido);
                break;
            
        }
        
        candidatoRepositorio.editar(candidato);
        carregarTabela();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidatoTela().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCandidato;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCandidatos;
    // End of variables declaration//GEN-END:variables
}
